---
title: "Rstudio et pipe"
author: "finistere2022"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R et le chaînage d'opérations

```{r}
x |> 
   mean()

```

# Ecriture de fonctions :

```{r}
function(x) x + 1 
\(x) x + 1

quote(x |> 
   mean())

quote (x %>%
   mean())
```

##### --- Time difference ---

```{r}
Time_old <- sapply(1:1000, function(k)
  {start.time <- Sys.time()
mtcars %>% 
   lm(mpg ~ disp, data = .)
end.time <- Sys.time()
time.taken <- end.time - start.time
return(time.taken)})

Time_new <- sapply(1:1000, function(k)
  {start.time <- Sys.time()
mtcars |> 
   (function(x) lm(mpg ~ cyl, data = x))()
end.time <- Sys.time()
time.taken <- end.time - start.time
return(time.taken)})

meanTime_new <- mean(Time_new);meanTime_old <- mean(Time_old)
sdTime_new <- sd(Time_new);sdTime_old <- sd(Time_old)
```

# Addins

```{r}

reorder_library <- function() {
# Recupère le contenu du script courant
script <- rstudioapi::getActiveDocumentContext()$contents
# Identifie les lignes avec des appels à library()
indice_library <- stringr::str_which(
string = script,
pattern = "library\\([:alnum:]+\\)"
)
# on les remplace par une section avec le nom du package
rng_library <- Map(c, Map(c, indice_library, 1), Map(c, indice_library, 80))
rstudioapi::modifyRange(
location = rng_library, # position des library() dans le script
text = stringr::str_replace(
string = script[indice_library],
pattern = "library\\(([:alnum:]+)\\)",
replacement = "# \\1 ----"
)
)
# on les place les appels à library() en début de script
rstudioapi::insertText(
location = c(1, 1), # début du script
text = stringr::str_c(c(
"\n# Packages ----",
script[indice_library]
), collapse = "\n")
)
return(invisible())
}


library(readr)
moi <- "ok"
library(dplyr)
toi <- 15
library(ggplot2)
nous <- 17
```
