---
title: "SIG avec SF"
author: "Pierre Barbillon, Anna Bonnet, Pierre Gloaguen"
date: "2022-08-23"
output: 
  html_document:
    df_print: paged
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r sig_required_packages}
library(sf)
library(ggplot2)
```


# Données 

Les données utilisées sont issues de ce [tutoriel sur la géomatique avec R](https://rcarto.github.io/geomatique_avec_r/) et accessible sur leur répertoire `Github`.

```{r sig_load_data}
communes <- st_read("https://github.com/rCarto/geomatique_avec_r/blob/main/data/lot46.gpkg?raw=true",
               layer="commune")

route <- st_read("https://github.com/rCarto/geomatique_avec_r/blob/main/data/lot46.gpkg?raw=true", 
                 layer = "route", quiet = TRUE)

population_brute <- read.csv("https://github.com/rCarto/geomatique_avec_r/raw/main/data/pop.csv")
```

# Visualisation

La première étape est de représenter les objets spatiaux. Ces objets sont de la classe `sf`.

```{r}
is(communes)
is(route)
```

